export type Treatment = 'read' | 'quiet' | 'unread'

/**
 * Every kind dsh knows, restated so a pin that adds one fails a test. Quiet has no row in dsh web's
 * chat; unread has one no feature here draws yet, so the fallback draws it.
 */
export const kinds: Readonly<Record<string, Treatment>> = {
  'agent-preset/selected': 'quiet',
  'agent/inbox/spliced': 'quiet',
  'approval/asked': 'read',
  'approval/decided': 'read',
  'approval/policy': 'quiet',
  'assistant/attempt': 'quiet',
  'assistant/message': 'read',
  'command/done': 'read',
  'command/run': 'read',
  'compaction/end': 'read',
  'compaction/prune': 'quiet',
  'compaction/start': 'read',
  'compaction/summary': 'read',
  'deliverables/presented': 'unread',
  'developer/message': 'read',
  'feedback/message-delete': 'quiet',
  'feedback/message-put': 'quiet',
  'feedback/record': 'quiet',
  'goal/change': 'quiet',
  'hook/invoked': 'quiet',
  'hook/result': 'quiet',
  'image/offload': 'quiet',
  'llm/retry': 'unread',
  'llm/retry-started': 'unread',
  'model/selection': 'quiet',
  'permission/preset': 'quiet',
  'plan/mode': 'quiet',
  'request/context': 'quiet',
  'request/header': 'quiet',
  'sandbox/mode': 'quiet',
  'schedule/change': 'quiet',
  'session-log-deepseek/delivery-accepted': 'quiet',
  'session/end-seed': 'quiet',
  'session/title': 'quiet',
  'session/title-llm-request': 'quiet',
  'step/end': 'read',
  'step/start': 'read',
  'subagent/catalog': 'quiet',
  'subagent/descriptor': 'quiet',
  'subagent/model-selection-policy': 'quiet',
  'system/message': 'quiet',
  'team/member': 'quiet',
  'team/message/delivered': 'quiet',
  'team/message/queued': 'quiet',
  'team/task': 'quiet',
  'todo/write': 'quiet',
  'tool-workflow/agent-end': 'unread',
  'tool-workflow/agent-start': 'unread',
  'tool-workflow/run-end': 'unread',
  'tool-workflow/run-start': 'unread',
  'tool/call': 'read',
  'tool/ptc-dispatch': 'unread',
  'tool/ptc-dispatch-start': 'unread',
  'tool/result': 'read',
  'turn/end': 'read',
  'turn/start': 'read',
  'user/message': 'read',
  'web/deepseek-search-llm-request': 'quiet',
  'workspace/changes': 'unread',
}
